### PR TITLE
Update to parent to community 2.16, remove stuff from pom.xml that is now in parent

### PR DESCRIPTION
**Pull request by ahousing**
Note that although this component is deprecated, it is still consumed by tools.wscat and truststore-maven-plugin.  Until those two components are also marked as deprecated, it seems worthwhile to at least update the copyright.

### CODE REVIEW

**Comment by dpwspoon** [comment]
I would rather update those components to use community.  It should be straight forward.  Then we can delete this project

**Comment by ahousing** [comment]
I was thinking that that would be a separately filed ticket (to be done sometime in the future), and this would be the "fix now".  If you're thinking it's just a "change of parent", then I guess it would be equivalent time.  (Maybe even faster.)  Is that what you're thinking?

**Comment by ahousing** [comment]
I've filed two other pull requests ([1](https://github.com/kaazing/truststore-maven-plugin/pull/6), [2](https://github.com/kaazing/tools.wscat/pull/3)) to replace this one.  Assuming that those go in, I will remove all content like https://github.com/kaazing/gateway.client.ios, only pointing to community.

**Comment by dpwspoon** [comment]
@ahousing Thanks, merged the other two.  I'm fine with this being moved offline as it as been deprecated for ever and wasn't really migrated into community, (just replaced).  If you do want to do that work latter feel free to remove all content and just add a README saying this project is dead

**Pull request closed without merging**
